language: python
python:
  - "3.6"
  
cache: pip
  
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
  - cd test
  - nosetests --with-coverage --cover-test --cover-package=test
  - coverage report
  - cd ..
  
after_success:
  - coveralls